### ISSUE TITLE
Sring Boot 

### ISSUE THREAD

**Issue by qyuubo** [ggggborn/SpringCloud-acimage#2]
有 Sring Boot 版本吗？Spring Cloud 有点复杂

**Comment by ggggborn** [comment]
没有哦。这项目确实部署很麻烦，不要尝试去部署了，因为我部署文档都没写 (ฅ´ω`ฅ)

**Comment by qyuubo** [comment]
那怎么用啊？

**Comment by ggggborn** [comment]
没法直接用，放弃部署吧，别浪费时间了

**Comment by qyuubo** [comment]
作者，你不再拯救一下吗？

**Comment by ggggborn** [comment]
这太麻烦了，我自己部署都要部署一个下午，你们要是自己部署肯定更久，甚至会出现奇奇怪怪的问题。建议参考其它开源项目做毕业设计（O(∩_∩)O哈哈~）
